### ISSUE TITLE
Random123 has moved

### ISSUE THREAD

**Issue by maximerischard** [awllee/RNGPool.jl#1]
Random123 has moved to its own repository at https://github.com/sunoru/Random123.jl which is causing some import problems in RNGPool:

```
[ Info: Precompiling RNGPool [c7fc2d14-d53c-5e81-ac30-66aba9c03525]
ERROR: LoadError: UndefVarError: Random123 not defined
Stacktrace:
 [1] include at ./boot.jl:326 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:328 [inlined]
 [6] eval(::Expr) at ./client.jl:404
 [7] top-level scope at ./none:3
in expression starting at <JULIA_DEPOT>/packages/RNGPool/NsExu/src/RNGPool.jl:3
```

**Comment by awllee** [comment]
Thanks, I noticed this too and was waiting for [this](https://github.com/JuliaLang/METADATA.jl/pull/21552) to be merged.

The fix has now been released, but will likely take some time itself to be merged into METADATA. You could manually `add RNGPool#master` in the mean time.

**Comment by awllee** [comment]
Actually, the release got merged very quickly. Please reopen if there are any issues.
